<?php
namespace Database\Seeders;

use App\Models\BrandVehicle;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BrandTableSeeder extends Seeder
{
    public function run()
    {
        $brands = [
            ['id'=>1, 'name'=>'ACADIAN'],
            ['id'=>2, 'name'=>'ACURA'],
            ['id'=>3, 'name'=>'ALFA ROMEO'],
            ['id'=>4, 'name'=>'AMERICAN MOTORS'],
            ['id'=>5, 'name'=>'ARO'],
            ['id'=>6, 'name'=>'ASIA MOTORS'],
            ['id'=>7, 'name'=>'ASTON MARTIN'],
            ['id'=>8, 'name'=>'AUDI'],
            ['id'=>9, 'name'=>'AUSTIN'],
            ['id'=>10, 'name'=>'AUTORRAD'],
            ['id'=>11, 'name'=>'BEIGING'],
            ['id'=>12, 'name'=>'BMW'],
            ['id'=>13, 'name'=>'BUICK'],
            ['id'=>14, 'name'=>'BYD'],
            ['id'=>15, 'name'=>'CADILLAC'],
            ['id'=>16, 'name'=>'CHANGAN'],
            ['id'=>17, 'name'=>'CHERY'],
            ['id'=>18, 'name'=>'CHEVROLET'],
            ['id'=>19, 'name'=>'CHRYSLER'],
            ['id'=>20, 'name'=>'CITROEN'],
            ['id'=>21, 'name'=>'COMMER'],
            ['id'=>22, 'name'=>'DACIA'],
            ['id'=>23, 'name'=>'DAEWOO'],
            ['id'=>24, 'name'=>'DAIHATSU'],
            ['id'=>25, 'name'=>'DATSUN'],
            ['id'=>26, 'name'=>'DODGE'],
            ['id'=>27, 'name'=>'DONGFENG'],
            ['id'=>28, 'name'=>'F.S.O.'],
            ['id'=>29, 'name'=>'FERRARI'],
            ['id'=>30, 'name'=>'FIAT'],
            ['id'=>31, 'name'=>'FORD'],
            ['id'=>32, 'name'=>'FOTON'],
            ['id'=>33, 'name'=>'G.M.C.'],
            ['id'=>34, 'name'=>'GEELY'],
            ['id'=>35, 'name'=>'GREAT WALL'],
            ['id'=>36, 'name'=>'HAFEI'],
            ['id'=>37, 'name'=>'HAIMA'],
            ['id'=>38, 'name'=>'HILLMAN'],
            ['id'=>39, 'name'=>'HONDA'],
            ['id'=>40, 'name'=>'HYUNDAI'],
            ['id'=>41, 'name'=>'INTERNATIONAL'],
            ['id'=>42, 'name'=>'ISUZU'],
            ['id'=>43, 'name'=>'JAC'],
            ['id'=>44, 'name'=>'JAGUAR'],
            ['id'=>45, 'name'=>'JEEP'],
            ['id'=>46, 'name'=>'JMC'],
            ['id'=>47, 'name'=>'KIA MOTORS'],
            ['id'=>48, 'name'=>'LADA'],
            ['id'=>49, 'name'=>'LANCIA'],
            ['id'=>50, 'name'=>'LAND ROVER'],
            ['id'=>51, 'name'=>'LEXUS'],
            ['id'=>52, 'name'=>'LIFAN'],
            ['id'=>53, 'name'=>'LINCOLN'],
            ['id'=>54, 'name'=>'LOTUS'],
            ['id'=>55, 'name'=>'MAHINDRA'],
            ['id'=>56, 'name'=>'MASERATI'],
            ['id'=>57, 'name'=>'MAZDA'],
            ['id'=>58, 'name'=>'MERCEDES BENZ'],
            ['id'=>59, 'name'=>'MERCURY'],
            ['id'=>60, 'name'=>'MG'],
            ['id'=>61, 'name'=>'MINI'],
            ['id'=>62, 'name'=>'MITSUBISHI'],
            ['id'=>63, 'name'=>'MORRIS'],
            ['id'=>64, 'name'=>'NISSAN'],
            ['id'=>65, 'name'=>'NSU'],
            ['id'=>66, 'name'=>'OLDSMOBILE'],
            ['id'=>67, 'name'=>'OPEL'],
            ['id'=>68, 'name'=>'PEUGEOT'],
            ['id'=>69, 'name'=>'PLYMOUTH'],
            ['id'=>70, 'name'=>'POLSKI FIAT'],
            ['id'=>71, 'name'=>'PONTIAC'],
            ['id'=>72, 'name'=>'PORSCHE'],
            ['id'=>73, 'name'=>'PROTON'],
            ['id'=>74, 'name'=>'PUMA'],
            ['id'=>75, 'name'=>'RENAULT'],
            ['id'=>76, 'name'=>'ROVER'],
            ['id'=>77, 'name'=>'SAAB'],
            ['id'=>78, 'name'=>'SAEHAN'],
            ['id'=>79, 'name'=>'SAMSUNG'],
            ['id'=>80, 'name'=>'SEAT'],
            ['id'=>81, 'name'=>'SIMCA'],
            ['id'=>82, 'name'=>'SKODA'],
            ['id'=>83, 'name'=>'SMA'],
            ['id'=>84, 'name'=>'SSANGYONG'],
            ['id'=>85, 'name'=>'SUBARU'],
            ['id'=>86, 'name'=>'SUZUKI'],
            ['id'=>87, 'name'=>'TATA'],
            ['id'=>88, 'name'=>'TOYOTA'],
            ['id'=>89, 'name'=>'VOLKSWAGEN'],
            ['id'=>90, 'name'=>'VOLVO'],
            ['id'=>91, 'name'=>'WILLYS'],
            ['id'=>92, 'name'=>'YUGO'],
            ['id'=>93, 'name'=>'ZASTAVA'],
            ['id'=>94, 'name'=>'ZOTYE'],
            ['id'=>95, 'name'=>'ZX'],
            ['id'=>96, 'name'=>'BRILLIANCE'],
            ['id'=>97, 'name'=>'INFINITI'],
            ['id'=>98, 'name'=>'MCLAREN'],
            ['id'=>99, 'name'=>'MORGAN'],
            ['id'=>100, 'name'=>'CHANGHE'],
            ['id'=>101, 'name'=>'ROLLS ROYCE'],
            ['id'=>102, 'name'=>'SG'],
            ['id'=>103, 'name'=>'GAC GONOW'],
            ['id'=>104, 'name'=>'LANDWIND'],
            ['id'=>105, 'name'=>'FAW'],
            ['id'=>106, 'name'=>'BAIC'],
            ['id'=>107, 'name'=>'HAVAL'],
            ['id'=>108, 'name'=>'CATERHAM'],
            ['id'=>109, 'name'=>'LAMBORGHINI'],
            ['id'=>110, 'name'=>'BENTLEY'],
            ['id'=>111, 'name'=>'KENBO'],
            ['id'=>112, 'name'=>'DS AUTOMOBILES'],
            ['id'=>113, 'name'=>'MAXUS'],
            ['id'=>114, 'name'=>'DFSK'],
            ['id'=>115, 'name'=>'RAM'],
            ['id'=>116, 'name'=>'ZNA'],
            ['id'=>117, 'name'=>'KARMA'],
            ['id'=>118, 'name'=>'KYC'],
            ['id'=>119, 'name'=>'GAC'],
            ['id'=>120, 'name'=>'JETOUR']
        ];
        foreach ($brands as $brand) {
            $createBrand = new BrandVehicle();
            $createBrand->name = $brand['name'];
            $createBrand->slug = Str::slug($brand['name']);
            $createBrand->save();
        }
    }
}
